language: generic

sudo: required
services: 
  - docker 

before_install:
  - docker build -t fflores85/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true fflores85/docker-react npm run test 